name: seaflux-dev
channels:
  - defaults
dependencies:
  - python==3.7
  - pip
  - pytest-cov
  - flake8
  - wheel
  - xarray
  - black
  - isort
  - pandas
  - numpy
  - pip:
    - pre-commit
    - mkdocs
    - pooch


