# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  pull_request: {}
  push:
    branches: master
    tags: "*"

jobs:
  test:
    name: TEST (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]  # "macos-latest", "windows-latest"]
        python-version: ["3.7"]  # ["3.6", "3.7", "3.8"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v1
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          environment-file: dev-environment.yml
          activate-environment: seaflux-dev

      - shell: bash -l {0}
        run: |
            isort --recursive --diff .
            black -l 88 --check .
            flake8 --max-line-length=88
            pytest --cov --cov-fail-under=20
